from pathlib import Path

path = Path('app/src/main/assets/www/index.html')
s = path.read_text(encoding='utf-8')

old_economic = "function invoiceEconomicTotal(cardId,m){let rows=installments(m).filter(x=>x.card?.id==cardId);if(!rows.some(x=>x.purchase?.economicImpact==='neutral'))return invoiceTotal(cardId,m);let p=rows.filter(x=>x.purchase?.economicImpact!=='neutral').reduce((sum,x)=>sum+x.amount,0),a=invoiceAdjustments(cardId,m).reduce((sum,x)=>sum+x.amount,0);return Math.round((p+a)*100)/100}"
new_economic = "function invoiceEconomicTotal(cardId,m){let rows=installments(m).filter(x=>x.card?.id==cardId),neutral=rows.filter(x=>x.purchase?.economicImpact==='neutral').reduce((sum,x)=>sum+x.amount,0);return Math.max(0,Math.round((invoiceTotal(cardId,m)-neutral)*100)/100)}"
if s.count(old_economic) != 1:
    raise SystemExit(f'invoiceEconomicTotal: expected 1 match, got {s.count(old_economic)}')
s = s.replace(old_economic, new_economic, 1)

old_status = "function invoiceDisplayStatus(cardId,m){\n let st=invoiceStatus(cardId,m),total=invoiceTotal(cardId,m);\n if(st.paidAmount>=total-.01&&total>0)return'paid';"
new_status = "function invoiceDisplayStatus(cardId,m){\n let st=invoiceStatus(cardId,m),total=invoiceTotal(cardId,m);\n if(st.historicalOnly&&(st.paidAmount||0)>0)return'paid';\n if(st.paidAmount>=total-.01&&total>0)return'paid';"
if s.count(old_status) != 1:
    raise SystemExit(f'invoiceDisplayStatus: expected 1 match, got {s.count(old_status)}')
s = s.replace(old_status, new_status, 1)

old_modal = "root.innerHTML=`<div class=\"modal\" role=\"dialog\" aria-modal=\"true\" aria-label=\"Revisar classificação financeira\"><div class=\"head\"><div><h2>Revisar classificação</h2><p>${sfpEsc(item.desc||'Movimentação')} · ${sfpEsc(item.date||item.purchaseDate||'')}</p></div><button class=\"btn2\" id=\"financialReviewCancel\">Cancelar</button></div><div class=\"note\">${isPurchase?'Este item continuará como débito/obrigação da fatura. A escolha abaixo altera apenas o impacto econômico nos relatórios e orçamento.':'Escolha o que esta movimentação representa economicamente. O SFP não altera o valor nem a data.'}</div><label>O que isto representa?<select id=\"financialReviewNature\">${options}</select></label><label id=\"financialReviewCategoryWrap\">Categoria<select id=\"financialReviewCategory\">${CATEGORIES.map(c=>`<option ${c===currentCategory?'selected':''}>${sfpEsc(c)}</option>`).join('')}</select></label><div class=\"section-actions\"><button class=\"btn\" id=\"financialReviewSave\">Salvar classificação</button></div></div>`;\n  const sync=()=>{let n=$('financialReviewNature').value;$('financialReviewCategoryWrap').classList.toggle('hidden',['transfer','card-payment','neutral'].includes(n))};"
new_modal = "root.innerHTML=`<div class=\"modal\" role=\"dialog\" aria-modal=\"true\" aria-label=\"Revisar classificação financeira\"><div class=\"head\"><div><h2>Revisar classificação</h2><p>${sfpEsc(item.desc||'Movimentação')} · ${sfpEsc(item.date||item.purchaseDate||'')}</p></div><button class=\"btn2\" id=\"financialReviewCancel\">Cancelar</button></div><div class=\"note\">${isPurchase?'Este item continuará como débito/obrigação da fatura. A escolha abaixo altera apenas o impacto econômico nos relatórios e orçamento.':'Escolha o que esta movimentação representa economicamente. O SFP não altera o valor nem a data.'}</div><label>O que isto representa?<select id=\"financialReviewNature\">${options}</select></label><label id=\"financialReviewCategoryWrap\">Categoria<select id=\"financialReviewCategory\">${CATEGORIES.map(c=>`<option ${c===currentCategory?'selected':''}>${sfpEsc(c)}</option>`).join('')}</select></label>${isPurchase?'':`<label id=\"financialReviewCounterpartWrap\" class=\"hidden\">Outra conta da transferência<select id=\"financialReviewCounterpart\">${state.accounts.filter(a=>a.id!=item.accountId).map(a=>`<option value=\"${a.id}\">${sfpEsc(a.name)} • ${brl(accountBalance(a.id))}</option>`).join('')}</select><small>O SFP usará esta conta como a outra ponta da transferência e preservará valor e data.</small></label>`}<div class=\"section-actions\"><button class=\"btn\" id=\"financialReviewSave\">Salvar classificação</button></div></div>`;\n  const sync=()=>{let n=$('financialReviewNature').value;$('financialReviewCategoryWrap').classList.toggle('hidden',['transfer','card-payment','neutral'].includes(n));if(!isPurchase&&$('financialReviewCounterpartWrap'))$('financialReviewCounterpartWrap').classList.toggle('hidden',n!=='transfer')};"
if s.count(old_modal) != 1:
    raise SystemExit(f'review modal: expected 1 match, got {s.count(old_modal)}')
s = s.replace(old_modal, new_modal, 1)

old_save = "  $('financialReviewSave').onclick=async()=>{let n=$('financialReviewNature').value,cat=$('financialReviewCategory').value||'Outros';\n    if(isPurchase){if(n==='transfer'){item.economicImpact='neutral';item.semanticClass='user_card_transfer';item.category='Transferência'}else{item.economicImpact='economic';item.semanticClass='user_expense';item.category=cat}}\n    else if(n==='transfer'){item.economicImpact='neutral';item.semanticClass='user_transfer';item.category='Transferência'}\n    else if(n==='card-payment'){item.kind='expense';item.economicImpact='neutral';item.semanticClass='invoice_payment';item.category='Cartão'}\n    else if(n==='neutral'){item.economicImpact='neutral';item.semanticClass='user_neutral'}\n    else{item.kind=n==='income'?'income':'expense';item.economicImpact='economic';item.semanticClass=n==='income'?'user_income':'user_expense';item.category=cat}\n    item.classificationConfidence=1;item.classificationReason='Classificado manualmente pelo usuário na Auditoria.';\n    await save('Revisar classificação financeira');root.className='hidden';root.replaceChildren();renderAll();showFeedback('Classificação salva. A integridade financeira foi recalculada.',{title:'Revisão concluída',type:'success'});\n  };"
new_save = "  $('financialReviewSave').onclick=async()=>{let n=$('financialReviewNature').value,cat=$('financialReviewCategory').value||'Outros';\n    if(isPurchase){if(n==='transfer'){item.economicImpact='neutral';item.semanticClass='user_card_transfer';item.category='Transferência'}else{item.economicImpact='economic';item.semanticClass='user_expense';item.category=cat}}\n    else if(n==='transfer'){\n      const counterpartId=+$('financialReviewCounterpart')?.value;if(!counterpartId||counterpartId==item.accountId||!account(counterpartId))return toast('Escolha a outra conta da transferência.','warning');\n      const originalKind=item.kind,fromId=originalKind==='income'?counterpartId:item.accountId,toId=originalKind==='income'?item.accountId:counterpartId;\n      state.transfers.push({id:uid(),desc:item.desc,amount:Math.abs(item.amount),date:item.date,fromId,toId,tags:[...new Set([...(item.tags||[]),'auditoria','transferência'])],statementKey:item.statementKey||null,balanceImpact:item.balanceImpact!==false,semanticClass:'user_transfer',classificationConfidence:1,classificationReason:'Convertido em transferência entre contas pelo usuário na Auditoria.',sourceTransactionId:item.id,createdAt:item.createdAt||Date.now()});\n      state.transactions=state.transactions.filter(t=>t.id!==item.id);\n    }\n    else if(n==='card-payment'){item.kind='expense';item.economicImpact='neutral';item.semanticClass='invoice_payment';item.category='Cartão'}\n    else if(n==='neutral'){item.economicImpact='neutral';item.semanticClass='user_neutral'}\n    else{item.kind=n==='income'?'income':'expense';item.economicImpact='economic';item.semanticClass=n==='income'?'user_income':'user_expense';item.category=cat}\n    if(!(n==='transfer'&&!isPurchase)){item.classificationConfidence=1;item.classificationReason='Classificado manualmente pelo usuário na Auditoria.'}\n    await save('Revisar classificação financeira');root.className='hidden';root.replaceChildren();renderAll();showFeedback(n==='transfer'&&!isPurchase?'Transferência registrada com as duas contas. A integridade financeira foi recalculada.':'Classificação salva. A integridade financeira foi recalculada.',{title:'Revisão concluída',type:'success'});\n  };"
if s.count(old_save) != 1:
    raise SystemExit(f'review save: expected 1 match, got {s.count(old_save)}')
s = s.replace(old_save, new_save, 1)

path.write_text(s, encoding='utf-8')
print('audit review follow-up applied')
